base:
  project: Wafer-Quality-Project
  random_state: 42
  target_col: Output

data_source:
  batch_files: Traning_Batch_Files

data_preparation:
  traning_db: Traning.db
  traning_db_dir: Traning_Database
  schema_traning: config/schema_traning.json

pred_data_preparation:
  prediction_db: Prediction.db
  prediction_db_dir: Prediction_Database
  schema_prediction: config/schema_prediction.json

traning:
  random_forest:
    cv: 5
    verbose: 3
    param_grid:
      n_estimators:
        - 10
        - 50
        - 100
        - 130
      criterion:
        - gini
        - entropy
      max_depth:
        - 2
        - 4
      max_features:
        - auto
        - log2
  xg_boot:
    cv: 5
    verbose: 3
    param_grid:
      learning_rate:
        - 0.5
        - 0.7
